### ISSUE TITLE
JsonSerializationException: Could not find member 'logprobs' on object of type 'ChatChoice'. Path 'choices[0].logprobs', line 13, position 17.

### ISSUE THREAD

**Issue by MrKamikazee** [srcnalt/OpenAI-Unity#108]
I don't know what happen, but yesterady this work, and today not.

1. Play the project
2. Send some message
3. Wait for the error

![image](https://github.com/srcnalt/OpenAI-Unity/assets/64284557/1243d872-3d5b-4343-85b3-0d608263fd0f)

 - OS: Windows 11
 - Unity Version: 2022.3.15f1
 - Plugin Version: Last (0.1.16)

**Comment by mhhk88** [comment]
The same thing happened to me. It was Ok until yesterday. 
I am curious about the chatGPT API version that is currently used without problems.

**Comment by tunyawat** [comment]
Modify the DataTypes.cs as follow
    
    
    public struct ChatChoice
    {
        public ChatMessage Message { get; set; }
        public ChatMessage Delta { get; set; }
        public int? Index { get; set; }
        public string FinishReason { get; set; }
        public bool logprobs {get; set; }
    }

**Comment by MrKamikazee** [comment]
It works, thanks!!!
