### ISSUE TITLE
Android build does not work

### ISSUE THREAD

**Issue by berkingokyolcu** [srcnalt/OpenAI-Unity#11]
On Unity, the program works flawless. I tried to build it for android. OpenAI does not answer on apk. Is it because we call ApiKey from our computer? If it is how can i implement api key on script? If it isn't what should i do to make this work?

**Comment by srcnalt** [comment]
Created a PR for this problem. Not a safe way to use it but helps with it. #12

**Comment by woelfle2004** [comment]
Many thanks Sercan for this fast response.
I will give it a try this evening.
I want to use my app on my own so there should be no safety problem...
On the other hand: the user can put his individual ApiKey when he starts the app...

**Comment by woelfle2004** [comment]
It works now on Android !!!
Brilliant work Sercan, many thanks !!!

**Comment by srcnalt** [comment]
Great news! Closing the issue then.
