### ISSUE TITLE
JsonSerializationException: Could not find member 'logprobs' on object of type 'ChatChoice'.

### ISSUE THREAD

**Issue by M4RITH** [srcnalt/OpenAI-Unity#112]
I am getting this error in Unity when trying to connect to OpenAI API :
https://pastebin.com/1e2RaPMC

1. Use the OpenAI API.
2. Make a request to the OpenAI API.
3. Observe the error related to the 'logsprobs' member.

This code was working fine the last time I checked which was about 4 weeks ago.

Environment:
 - OS: Windows 11 Home
 - Unity Version: 2022.3.13f1
 - Plugin Version: 0.1.15
 
This is my code:
https://pastebin.com/HZ1TcFU8

![Screenshot 2024-01-12 180953](https://github.com/srcnalt/OpenAI-Unity/assets/66554720/248049c3-d6b0-4380-b6bd-bf0d2105e571)

**Comment by ericnasanta** [comment]
OpenAI updated their API recently to include a boolean parameter called logprobs. 

The steps I took as a temporary solution, similar to this issue ( #102  )
1. Packages → OpenAIUnity → Runtime → DataTypes
2. Find ChatChoice struct
3. Add this line to the struct -> public bool logprobs { get; set; }

**Comment by srcnalt** [comment]
Hi @M4RITH,

The issue is solved in the 0.2.0, in Unity Package Manager you can update the package and it should work.
Can you try and let me know?

**Comment by M4RITH** [comment]
> Hi @M4RITH,
> 
> The issue is solved in the 0.2.0, in Unity Package Manager you can update the package and it should work. Can you try and let me know?

Hi Sarge,

Yeah, it's working after the update. 
Thank you so much.
