### ISSUE TITLE
JSON Serialization Exception on Android, Not in Editor

### ISSUE THREAD

**Issue by GavinR621** [srcnalt/OpenAI-Unity#114]
**Describe the bug**
ChatGPT is not returning any text, and is instead returning a json serialization exception in my android logcat. Works fine in the Unity editor, but not until I build to android does the issue come about.

**Screenshots**
![image](https://github.com/srcnalt/OpenAI-Unity/assets/57119450/e95219ce-6ff5-4188-851b-1dcfe1dac546)

**Environment (please complete the following information):**
 - OS: Android
 - Unity Version 2023.2.1f1
 - Plugin Version 0.2.0

**Comment by Yorcal** [comment]
I am facing the same issue,
I see that you have closed your request, what did you do?

**Comment by GavinR621** [comment]
> I am facing the same issue, I see that you have closed your request, what did you do?

It can be caused by a lack of internet connection. If you're 100% positive your device is connected to the internet, it could be (this was my case) caused by a setting in OpenXR.
![image](https://github.com/srcnalt/OpenAI-Unity/assets/57119450/8628a587-0b7a-4861-ab67-d74f140423cb)
![image](https://github.com/srcnalt/OpenAI-Unity/assets/57119450/9b7e4b08-e181-44c8-bf8d-f9e090c20935)

**Comment by Yorcal** [comment]
Thank you so much !! 
Everything is working now
