### ISSUE TITLE
Does this SDK support related questions?

### ISSUE THREAD

**Issue by devzhuchuanbo** [srcnalt/OpenAI-Unity#13]
Hi, thanks for your SDK, I wonder does it support related questions?
For example, I asked three questions, the second and third questions are related to the first one, and it seems that I can't get a satisfactory answer.

**Comment by srcnalt** [comment]
The SDK is a mere connector to the OpenAI API, I can do nothing to influence the answers other than the prompt you provide in the project you are making. You can check the ChatGPT sample in the package to see how you can chain the questions and answers to have a continuous conversation.
