### ISSUE TITLE
OpenAI Package cannot import

### ISSUE THREAD

**Issue by pablopalma** [srcnalt/OpenAI-Unity#2]
Hi, i'm following your tutorial, but i'm having issues to import OpenAI package from git URL.

Some idea how fix it? It seems like a issue from the package git.

![Screenshot_64](https://user-images.githubusercontent.com/5016992/212158024-4eab6e6d-9536-4da2-9228-bb8ef03f689c.png)

**Comment by srcnalt** [comment]
Hi, @pablopalma I just tried to import in 2020.3 LTS, 2021.3 LTS, and 2022.1. all worked fine without any JSON parse errors.
Could you tell me which Unity version are you using, so I can try to replicate the issue there?

**Comment by srcnalt** [comment]
Just checking the `package.json` again in VS code I realized Rider added a hidden [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) and I just removed it. In GitHub changes it still looks like nothing changed but this should help with the issue. Change is here: https://github.com/srcnalt/OpenAI-Unity/commit/21fe19ff87983952c313eb8f74d2b81aba1b9dd2

**Comment by pablopalma** [comment]
Hi, @srcnalt i imported in 2020.3.43 LTS and now is working. I think was the package.json change.
Thanks!
