### ISSUE TITLE
OpenAI. CreateCompletion () returns CreateCompletionResponse. Choices to null

### ISSUE THREAD

**Issue by Rongwenwen** [srcnalt/OpenAI-Unity#32]
Published to Hololens platforms, openai CreateCompletion () returns CreateCompletionResponse. Choices to null。But There is no problem in the unity editor.

**Comment by srcnalt** [comment]
Hi @Rongwenwen if you are using ill2cpp scripting can you change it to mono and try?

**Comment by spoullados** [comment]
Solved this issue by enabling the Internet (Client) capability
