### ISSUE TITLE
not working on IOS

### ISSUE THREAD

**Issue by rb15** [srcnalt/OpenAI-Unity#39]
hello , I am trying to include this Api to phone application , the app work fin in editor but when I build it in device it won't work.
I saw a simulare issue here https://github.com/srcnalt/OpenAI-Unity/issues/19 and the solution was to change backend script from IL2CPP to Mono and it works find on android but IOS only accept IL2CPP.
Is there any solution ?

**Comment by srcnalt** [comment]
Hi @rb15 v0.1.12 now comes with the new Newtonsoft Json release, which should help with this issue. Could you test it and let me know if it works?

**Comment by rb15** [comment]
Thanks it works now
