### ISSUE TITLE
Auth Error on WebGL

### ISSUE THREAD

**Issue by ChrisKlingler** [srcnalt/OpenAI-Unity#45]
Within the editor things communicate fine with OpenAI but when building and running a WebGL build I get the following response:

{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

Why is it the apiKey headers are not being passed on WebGL builds?

**Comment by srcnalt** [comment]
Hi @ChrisKlingler, WebGL app will not be able to reach the key through your local files. Alternatively, you can provide the API key to your OpenAiAPI ctor as a parameter to make it work. I made a video for ht here https://www.youtube.com/watch?v=DjX8mjBCMcg

**Comment by srcnalt** [comment]
Ah, this is interesting, it is a direct server error. I wonder if this could be related to firewalls etc. Could you tell me which version of Unity are you using so I can try to replicate it, this never happened to me before.

**Comment by srcnalt** [comment]
So if I understand correctly, this works in 2020 but not in 2022?

**Comment by srcnalt** [comment]
Building from Unity 2020.3.0f1 It works all right for me. I suspect it might be a network/firewall-related issue.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/3163281/234127571-d405396e-9f4c-4fec-ae5c-36e34127001c.png">

**Comment by MaximilianCroissant** [comment]
Is this solved? I run into the same issue. For test purposes the API key is hardcoded and everything works in the editor. But the WebGL build has the authentication error. I've tried 2020.3.0f1, 2021.3.22f1, and 2022.2.19f1.
