### ISSUE TITLE
Not working with WebGL builds

### ISSUE THREAD

**Issue by LucienMaman** [srcnalt/OpenAI-Unity#47]
Hi @srcnalt , thanks for this amazing project!
As with previous similar issues, I am stuck with my WebGL build. It works well in the editor but not in the web version where I got an error 400 when posting to https://api.openai.com/v1/chat/completions (ie, when sending a message) from the game hosted on my website.

I am developing on MacOS (M1 chip) and the editor version is 2021.3.22f1.
I tried to pull the latest code from the repo but still do not solve the issue.

Some of my build settings that might be of interest are attached.
Any help would be really appreciated :)

I'll keep you updated if I find any solution in the meantime.

Cheers.

<img width="674" alt="Capture d’écran 2023-04-25 à 13 06 19" src="https://user-images.githubusercontent.com/25378183/234258571-ec767f1a-9135-405d-bb64-2589e4256e8f.png">
<img width="367" alt="Capture d’écran 2023-04-25 à 13 05 59" src="https://user-images.githubusercontent.com/25378183/234258578-c2712924-6c91-4895-8672-6d7401dea137.png">

**Comment by srcnalt** [comment]
Hi @LucienMaman I was able to test on 3 different Unity versions and 2020.x and 2022.x worked, however 2021 is nor able to build it. Added a small table at the end of the readme file and I will update it as I can find more about which features break where.

**Comment by LucienMaman** [comment]
Hi @srcnalt, thanks for the support! However, I tried out to build it with the versions 2022.2.8f1 but also 2022.2.17f1, and I'm still receiving an error 400 when posting to https://api.openai.com/v1/chat/completions.

I double-checked, and it is working well in my editor. Any guess/hints I can try out to make it works?
Thanks again,

**Comment by srcnalt** [comment]
I will be able to get my hands on a MAC only 2 weeks later, I hope some can with Mac can take a look and check that.

**Comment by LucienMaman** [comment]
Thanks @srcnalt. I will post an update if I manage to find the bug before you get access to a MAC :)

**Comment by LucienMaman** [comment]
Quick update, it looks like a similar issue as in #21 

I tried the same debugging steps and it looks like the error comes from Newtonsoft as well. Not sure how to debug further yet.
