### ISSUE TITLE
JsonSerializationException: Could not find member 'id' on object of type 'CreateChatCompletionResponse' v0.1.12

### ISSUE THREAD

**Issue by ChrisKlingler** [srcnalt/OpenAI-Unity#53]
Hey @srcnalt , I'm seeing this issue in v0.1.12 with Unity 2022.2.16 running WebGL builds. Here is the JSON returned by OpenAI Chat Completion:

{"id":"chatcmpl-7Blu4ha7YR834teg22T0XYBdBk77D","object":"chat.completion","created":1683040104,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":70,"completion_tokens":58,"total_tokens":128},"choices":[{"message":{"role":"assistant","content":"Hello, it is a pleasure to be chatting with you today.\n\nI am feeling quite content at the moment, thank you for asking. How about yourself?\n\nDo you have any questions for me? I am happy to share my thoughts and insights on science, philosophy, and life in general."},"finish_reason":"stop","index":0}]}

But the library is throwing this error via Newtonsoft:

app.framework.js.br:10 JsonSerializationException: Could not find member 'id' on object of type 'CreateChatCompletionResponse'. Path 'id', line 1, position 6.
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x00000] in <00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---

Anything else I should adjust to get this to work?

**Comment by LucienMaman** [comment]
Hey @ChrisKlingler, I am facing a similar issue, I commented on a couple of steps I took in this issue: #47 -- it might help to troubleshoot.
I still did not figure out, so if any progress on your side, please let me know :)

**Comment by jackmca** [comment]
I have also encountered the same issue. Would very much like to hear a fix.

**Comment by jackmca** [comment]
**Update**: I was able to fix this error, but now no text is generated within the build.

The above error was caused for me due to Unity stripping Newtonsoft.Json from assembly when building for IL2CPP, to prevent this from occurring, you must edit the link.xml file located in the assets folder to include the line:

 `<assembly fullname="Newtonsoft.Json" preserve="all"/>`

**Comment by srcnalt** [comment]
Hi folks, I tried to bring prebuild link.xml support here #68 now the package contains a link.xm for preserving OpenAI.Runtime scope, which was the main issue. Newtonsoft didn't recognize the stripped types and returned null for them. I was able to get it working in WebGL build with high code stripping unity 2020+

I'd appreciate if you could also give it a try and see if all works fine.
