### ISSUE TITLE
Invalid Request Error

### ISSUE THREAD

**Issue by AnyNqm3** [srcnalt/OpenAI-Unity#63]
I am getting this error:
UnityEngine.Debug:LogError (object)
OpenAI.OpenAIApi/d__6`1<OpenAI.CreateCompletionResponse>:MoveNext () (at Library/PackageCache/com.srcnalt.openai-unity@8d6d57d5ae/Runtime/OpenAIApi.cs:88)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

Any Idea on how to fix it?

**Comment by jackmca** [comment]
Are you providing an organisation string in the API? I had this same error and by removing the organisation string, it fixed it for me.
