### ISSUE TITLE
Null reference related to layout rebuilder

### ISSUE THREAD

**Issue by DylanPipping** [srcnalt/OpenAI-Unity#64]
I'm not sure if any of you are experiencing this but I keep getting a null reference error everytime I click the send button. I'm not sure where the problem is located because when I checked if I have everything correctly it shows that I have and the problem is also not code based as far as I can see, to my knowledge at least.

I just went to my application, then run the start button, go to the NPC and speak to her and then see the error pop up.

![Schermafbeelding 2023-06-12 153330](https://github.com/srcnalt/OpenAI-Unity/assets/66719605/1f26eae8-f20b-47a4-956b-d6a79843519b)

What is supposed to happen is that the character should be responding after the send button is clicked

![Schermafbeelding 2023-06-12 153330](https://github.com/srcnalt/OpenAI-Unity/assets/66719605/1f26eae8-f20b-47a4-956b-d6a79843519b)

![Schermafbeelding 2023-06-12 153537](https://github.com/srcnalt/OpenAI-Unity/assets/66719605/b65d9b5e-0190-449f-bdbf-71d99a270028)

![Schermafbeelding 2023-06-12 153631](https://github.com/srcnalt/OpenAI-Unity/assets/66719605/185e97df-e8b9-4819-bba0-92c06a6723e2)
![Schermafbeelding 2023-06-12 153651](https://github.com/srcnalt/OpenAI-Unity/assets/66719605/dafffcbb-927b-4ed4-a21f-0bea3a9e38ed)
![Schermafbeelding 2023-06-12 153704](https://github.com/srcnalt/OpenAI-Unity/assets/66719605/f177286b-5dee-47b9-83a0-0597bab76b9f)

OS: Windows 11
Unity Version 2021.3.20f1
I used the latest version of this plugin for unity

some words in the pictures are dutch

**Comment by srcnalt** [comment]
Hi @DylanPipping,

The UI provided in the samples are for demonstration purposes and may not work stably. I'd suggest you to develop a solution that suits you game.
