### ISSUE TITLE
When microphone is off I get the word "you" in the "Text" field in the API response with Whisper

### ISSUE THREAD

**Issue by MahmoudAbusaqer** [srcnalt/OpenAI-Unity#65]
**Describe the bug**
Most often when the microphone is muted or there is no sound around I get the word "you" in the "Text" field from the API response to the Whisper API which is wired there should be nothing just an empty string.  

**To Reproduce**
1. Go to the Whisper Sample scene and add this line to the Whisper code in the EndRecording method: Debug.Log("response: " + res.Serialize());.
2. Click on Play and mute your microphone.
3. Scroll down on the console and see the result of the line we add in step 1.
4. See the error.

**Expected behavior**
When there is no sound around or the microphone is muted the "Text" field from the response of the Whisper API should have a value of an empty string "" not the word "you".

**Screenshots**
![image](https://github.com/srcnalt/OpenAI-Unity/assets/60627501/9ad6aee1-31d5-4170-bb40-779b941d75e7)

**Environment**
 - OS: Windows 10 Pro
 - Unity Version: 2021.3.19f1
 - Plugin Version: 0.1.12

**Comment by srcnalt** [comment]
Hi @MahmoudAbusaqer same happens to me too, and this is a OpenAI/Whisper related issue. Apparently it returns "you" for silence or white noise. There is nothing I can propose other than processing the audio in your solution and ignore such audio as input.
<img width="186" alt="image" src="https://github.com/srcnalt/OpenAI-Unity/assets/3163281/f4ede748-7c02-4e6b-af8c-ed53cf33f34b">
