### ISSUE TITLE
Invalid expression term on Import

### ISSUE THREAD

**Issue by Neraull** [srcnalt/OpenAI-Unity#7]
hi, i've just imported the package into unity (2019.4.38f1c1 LTS) on windows and it immediately gives me the following error:

Library\PackageCache\com.srcnalt.openai-unity@f06833f4ff\Runtime\OpenAIApi.cs(19,64): error CS1525: Invalid expression term '='

it seems to refer to the line: private Configuration Configuration => configuration ??= new Configuration(); 

Would you happen to know what the problem could be?

Thanks!

**Comment by srcnalt** [comment]
Hi @Neraull, this is a null-coalescing operator with the inline property. I use a newer C# compiler I suppose that must be the issue. Will make sure I am writing older and more common version. You can replace this line with 

```csharp
private Configuration Configuration
{
    get
    {
        if (configuration == null)
        {
            configuration = new Configuration();
        }
        return configuration;
    }
}
```

**Comment by Neraull** [comment]
Hi Srcnalt, thanks for the quick response!  

i replaced the line with the block of code above, and there are cascading errors that pop up in other classes.  lol

it first showed me that it couldn't make line 5 in IRsponse a public: public ApiError Error { get; set; }

then after fixing that, it now tells me: Assets\Samples\OpenAI Unity\0.1.2\DallE\DallE.cs(35,23): error CS1003: Syntax error, '(' expected

I'm assuming it's an issue on my end with an older compiler?

Thanks for the help.

**Comment by Neraull** [comment]
attaching images of what i'm seeing.

![image](https://user-images.githubusercontent.com/8577346/213686306-07c170c4-3e35-4132-b1c5-56dc9814ada9.png)

![image](https://user-images.githubusercontent.com/8577346/213686157-c89a0f73-d351-43ef-a8fb-8c30fdf9b8ad.png)

**Comment by srcnalt** [comment]
So seems like object creation with initial values should be like

- `var request = new RequestType(){ params... }` with `()` paranthesis.
- and using declaration after C# 8 does not need curly braces and disposes of when function block is reached.

I suppose I should reduce my C# version and have another pass on the whole code.

**Comment by Neraull** [comment]
ahh ok.  so it's more different compiler versions causing these issues.  Should i just wait for your next version then?

**Comment by srcnalt** [comment]
Updated the code to be C# 6 compatible and made a release #8 
v0.1.3 should be working fine. Could you update the package in Unity Package Manager and let me know if all works fine?

**Comment by Neraull** [comment]
Heya, 

I reimported the package again and it seems fine until i import the DallE sample.

then the following error pops up:

![image](https://user-images.githubusercontent.com/8577346/213845642-4d0fa138-1c3c-40b4-aa93-4e9416f09efe.png)

![image](https://user-images.githubusercontent.com/8577346/213845634-5a6b1c08-c4cf-4480-9a5e-7c7f4f6a076a.png)

**Comment by srcnalt** [comment]
Sorry forgot this one, you can wrap the content of the if block in there in a using block.

```csharp
using(var request = new UnityWebRequest(response.Data[0].Url))
{
  request.downloadHandler = new DownloadHandlerBuffer();
  request.SendWebRequest();

  while (!request.isDone) await Task.Yield();

  Texture2D texture = new Texture2D(2, 2);
  texture.LoadImage(request.downloadHandler.data);
  var sprite = Sprite.Create(texture, new Rect(0, 0, 256, 256), Vector2.zero, 1f);
  image.sprite = sprite;
}
```

**Comment by Neraull** [comment]
awesome!  completely works now for testing and base functions.  Thank you so much, you're awesome for doing this.
