### ISSUE TITLE
JsonSerializationException: Could not find member 'warning' on object of type 'CreateChatCompletionResponse'. Path 'warning', line 2, position 12.

### ISSUE THREAD

**Issue by nihatcagri** [srcnalt/OpenAI-Unity#73]
I was able to use the API without any issues until yesterday, but today I started getting this error without making any updates. I saw "Could not find member id" errors in previous posts, but I didn't see the "warning" message. I'm waiting for your assistance, thank you :)

**Comment by stavrosdidakis** [comment]
Same here

**Comment by CampbellJohn** [comment]
The model this library is using depreciated. It's giving a "warning" message in the json, but that's not a field we're expecting so it's throwing an error.

Here's the message OpenAI attached;

"warning": "This model version is deprecated and a newer version 'gpt-3.5-turbo-0613' is available. Migrate before September 13 to avoid disruption of service. Learn more https://platform.openai.com/docs/deprecations"

I changed the model version in ChatGPT.cs, and it's working for me again.

**Comment by gugeme** [comment]
it works.thanks!

**Comment by nihatcagri** [comment]
Thank you, worked ! 👍
