### ISSUE TITLE
JsonSerializationException: Could not find member 'warning' on object of type 'CreateChatCompletionResponse'. Path 'warning', line 2, position 12.

### ISSUE THREAD

**Issue by u431535** [srcnalt/OpenAI-Unity#74]
1. I use this to run is okay on July 11 & 12 (Taipei time).
2. but run it to have error on July 13 (Taipei time), even I create new unity project (pure) to test/run.
Error log:
JsonSerializationException: Could not find member 'warning' on object of type 'CreateChatCompletionResponse'. Path 'warning', line 2, position 12.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember,

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11
 - Unity Version 2022.3.1f1
 - Openai-Unity: 0.1.14

![errorLog](https://github.com/srcnalt/OpenAI-Unity/assets/30690956/518df651-67b4-46dc-aa9a-5348cde7ff22)

**Comment by Radlad-io** [comment]
Bump. Same thing started happening to a project I have deployed.

**Comment by BillO57** [comment]
Under what method are you placing that?

**Comment by Radlad-io** [comment]
The CreateChatCompletionResponse method.

**Comment by maiconcurriel** [comment]
public struct CreateChatCompletionResponse : IResponse
    {
        public ApiError Error { get; set; }
        public string Model { get; set; }
        public string Id { get; set; }
        public string Object { get; set; }
        public long Created { get; set; }
        public List<ChatChoice> Choices { get; set; }
        public Usage Usage { get; set; }        
        public string warning { get; set; }
    }

**Comment by BillO57** [comment]
Thank you! That fixed the issue.

**Comment by srcnalt** [comment]
Sorry for the late response folks. I've been away for a while. A version with the fix is released #75

**Comment by BillO57** [comment]
No problem, I really appreciate all that you have done here and on your YouTube channel.
