### ISSUE TITLE
how can i add max_tokens: 100 

### ISSUE THREAD

**Issue by julin171012** [srcnalt/OpenAI-Unity#79]
Hello, Scarlett
I have been using this project for some time, and sometimes chatgpt replies to me with long tokens. I want to reduce its response. But cannot add 'max_tokens': max_ Tokens, what can I do。

**Comment by srcnalt** [comment]
Hi @julin171012,

You can add it as `MaxTokens` in pascal case. You might as well add a word count restriction in your prompt saying `Respond using maximum x words.`

**Comment by julin171012** [comment]
wooo, thanks  .   u are correct.

**Comment by srcnalt** [comment]
Glad that worked, closing the issue.
